import prisma from "../lib/prisma";

async function main() {
  console.log("Seeding database...");

  // Create sample users
  const users = [
    {
      id: "user1",
      phoneNumber: "+212600000001",
      displayName: "Ahmed Bennani",
      email: "ahmed@example.com",
      whatsapp: "+212600000001",
      isActive: true,
    },
    {
      id: "user2",
      phoneNumber: "+212600000002",
      displayName: "Fatima Alaoui",
      email: "fatima@example.com",
      whatsapp: "+212600000002",
      isActive: true,
    },
    {
      id: "user3",
      phoneNumber: "+212600000003",
      displayName: "Youssef Tazi",
      email: "youssef@example.com",
      whatsapp: "+212600000003",
      isActive: true,
    },
    {
      id: "user4",
      phoneNumber: "+212600000004",
      displayName: "Sara El Amrani",
      email: "sara@example.com",
      whatsapp: "+212600000004",
      isActive: true,
    },
    {
      id: "user5",
      phoneNumber: "+212600000005",
      displayName: "Karim Bouazza",
      email: "karim@example.com",
      whatsapp: "+212600000005",
      isActive: true,
    },
  ];

  for (const user of users) {
    await prisma.user.upsert({
      where: { phoneNumber: user.phoneNumber },
      update: {},
      create: user,
    });
  }

  console.log("Users created");

  // Sample car data
  const cars = [
    {
      sellerId: "user1",
      title: "Toyota Corolla 2018",
      description:
        "Voiture en excellent état, entretien régulier, première main.",
      brand: "Toyota",
      model: "Corolla",
      year: 2018,
      mileage: 85000,
      price: 145000,
      location: "Casablanca",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000001",
      fuel: "ESSENCE" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user1",
      title: "BMW X3 2020",
      description: "SUV familial, tout équipé, garantie constructeur.",
      brand: "BMW",
      model: "X3",
      year: 2020,
      mileage: 45000,
      price: 380000,
      location: "Rabat",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000001",
      fuel: "DIESEL" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user2",
      title: "Mercedes C-Class 2019",
      description: "Berline de luxe, intérieur cuir, navigation GPS.",
      brand: "Mercedes",
      model: "C-Class",
      year: 2019,
      mileage: 62000,
      price: 320000,
      location: "Marrakech",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000002",
      fuel: "DIESEL" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user2",
      title: "Renault Clio 2017",
      description: "Citadine économique, idéale pour la ville.",
      brand: "Renault",
      model: "Clio",
      year: 2017,
      mileage: 95000,
      price: 85000,
      location: "Fès",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000002",
      fuel: "ESSENCE" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user3",
      title: "Audi A4 2021",
      description: "Voiture sportive, moteur puissant, boîte automatique.",
      brand: "Audi",
      model: "A4",
      year: 2021,
      mileage: 35000,
      price: 420000,
      location: "Casablanca",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000003",
      fuel: "ESSENCE" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user3",
      title: "Peugeot 208 2016",
      description: "Compacte dynamique, faible consommation.",
      brand: "Peugeot",
      model: "208",
      year: 2016,
      mileage: 110000,
      price: 75000,
      location: "Tanger",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000003",
      fuel: "ESSENCE" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user4",
      title: "Volkswagen Golf 2019",
      description: "Familiale polyvalente, espace intérieur généreux.",
      brand: "Volkswagen",
      model: "Golf",
      year: 2019,
      mileage: 58000,
      price: 195000,
      location: "Agadir",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000004",
      fuel: "DIESEL" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user4",
      title: "Hyundai Tucson 2022",
      description: "SUV moderne, technologie avancée.",
      brand: "Hyundai",
      model: "Tucson",
      year: 2022,
      mileage: 25000,
      price: 280000,
      location: "Rabat",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000004",
      fuel: "HYBRIDE" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user5",
      title: "Ford Focus 2018",
      description: "Berline confortable, idéale pour longs trajets.",
      brand: "Ford",
      model: "Focus",
      year: 2018,
      mileage: 78000,
      price: 125000,
      location: "Meknès",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000005",
      fuel: "ESSENCE" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user5",
      title: "Nissan Qashqai 2020",
      description: "SUV crossover, design élégant.",
      brand: "Nissan",
      model: "Qashqai",
      year: 2020,
      mileage: 42000,
      price: 260000,
      location: "Oujda",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000005",
      fuel: "DIESEL" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user1",
      title: "Kia Sportage 2019",
      description: "SUV robuste, parfait pour toutes les routes.",
      brand: "Kia",
      model: "Sportage",
      year: 2019,
      mileage: 55000,
      price: 220000,
      location: "Casablanca",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000001",
      fuel: "ESSENCE" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user2",
      title: "Opel Astra 2017",
      description: "Compacte fiable, entretien facile.",
      brand: "Opel",
      model: "Astra",
      year: 2017,
      mileage: 92000,
      price: 95000,
      location: "Rabat",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000002",
      fuel: "DIESEL" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user3",
      title: "Mazda CX-5 2021",
      description: "SUV premium, performances exceptionnelles.",
      brand: "Mazda",
      model: "CX-5",
      year: 2021,
      mileage: 38000,
      price: 350000,
      location: "Marrakech",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000003",
      fuel: "ESSENCE" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user4",
      title: "Citroën C3 2018",
      description: "Citadine fun, économique et pratique.",
      brand: "Citroën",
      model: "C3",
      year: 2018,
      mileage: 67000,
      price: 78000,
      location: "Fès",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000004",
      fuel: "ESSENCE" as const,
      transmission: "MANUAL" as const,
      bodyType: "BERLINE" as const,
      condition: "OCCASION" as const,
    },
    {
      sellerId: "user5",
      title: "Jeep Compass 2020",
      description: "SUV aventurier, prêt pour toutes les aventures.",
      brand: "Jeep",
      model: "Compass",
      year: 2020,
      mileage: 49000,
      price: 290000,
      location: "Tanger",
      images: ["/car-service.png"],
      whatsappNumber: "+212600000005",
      fuel: "DIESEL" as const,
      transmission: "AUTOMATIC" as const,
      bodyType: "SUV" as const,
      condition: "OCCASION" as const,
    },
  ];

  for (const car of cars) {
    await prisma.car.create({
      data: car,
    });
  }

  console.log("Cars created");
  console.log("Seeding completed");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
